
project_id = "isjjzddntanbjopqylic"
name = "boost-doctor"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
webhook_enabled = false
webhook_url = "http://localhost:54323"
webhook_headers = { foo = "bar" }
max_cases = 100

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[auth]
enable_signup = false
site_url = "https://app.boost.doctor"
additional_redirect_urls = ["https://app.boost.doctor", "http://localhost:5173"]
hook_timeout_seconds = 5
jwt_expiry_seconds = 3600

[auth.email]
enable_confirmations = false
double_confirm_changes = false
mailer_autoconfirm = true

[auth.sms]
verify_sms_template = "Your verification code is {{ .Code }}"

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.third_party.clerk]
enabled = true
domain = "funky-labrador-91.clerk.accounts.dev"
auto_link_users = true

[inbucket]
enabled = false
port = 54324
pop3_port = 54325
smtp_port = 54326
storage_type = "memory"

[analytics]
enabled = false
port = 54327

[storage]
enabled = true

[vector]
enabled = false

[functions]
port = 54328
serve_port = 54330
function_pattern = "**/*.func.ts"
account_id = ""

[functions.clerk-webhook]
verify_jwt = false

[migrations]
enabled = true

[observability]
enabled = false
