
isjjzddntanbjopqylic

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[auth.third_party.clerk]
enabled = true
domain = "funky-labrador-91.clerk.accounts.dev"

